{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "virtual-ac.serviceAccountName" . }}
  labels:
    {{- include "virtual-ac.labels" . | nindent 4 }}
{{- end }}
