apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "broadlink-mqtt.fullname" . }}
  labels:
    {{- include "broadlink-mqtt.labels" . | nindent 4 }}
data:
  mqtt.conf: {{- toYaml .Values.config | nindent 2 }}
