mqtt_broker = 'tcp://localhost:1883'
status_topic = 'heater/status/Kitchen'
update_topic = 'heater/update/Kitchen'
thermal_sensor_topic = 'zigbee/status/ThermalSensor/Kitchen'
sonoff_relay_ip = '192.168.1.50'
