{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "boiler.serviceAccountName" . }}
  labels:
    {{- include "boiler.labels" . | nindent 4 }}
{{- end }}
