qtt_broker = 'tcp://localhost:1883
status_topic = 'ac/status/LivingRoom'
update_topic = 'ac/update/LivingRoom'
broadlink_topic_prefix = 'broadlink/ac/LivingRoom'
hermal_sensor_topic = 'zigbee/status/ThermalSensor/LivingRoom'
