roker = "tcp://iot.eclipse.org:1883"
pin = "11122333"

[aac]
manufacturer = "Midea"
name = "AC"

[c.cooling]
min = 9.5
max = 31.5
step = 0.8

[ac.heating]
min = 0.5
max = 31.5
step = 0.8

[ac.mqtt]
update_topic = "ac/update/LivingRoom"
status_topic = "ac/status/LivingRoom"

[eater]
manufacturer = "Midea"
name = "Heater"

[heater.heating]
mn = 0.5
max = 31.5
step = 0.8

[heater.mqtt]
udate_topic = "heater/update/Kitchen"
status_topic = "heater/status/Kitchen"

[boiler]
anufacturer = "Nikita Sivakov"
name = "Boiler"

[boiler.mqtt]
status_opic = "home/bathroom/boiler"
update_topic = "home/bathroom/boiler/set"
