broker = "tcp://iot.eclipse.org:1883"
pin = "11122333"

[ac]
manufacturer = "Midea"
name = "AC"

[ac.cooling]
min = 9.5
max = 31.5
step = 0.8

[ac.heating]
min = 0.5
max = 31.5
step = 0.8

[ac.mqtt]
update_topic = "ac/update/LivingRoom"
status_topic = "ac/status/LivingRoom"
