{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hap-ui.serviceAccountName" . }}
  labels:
    {{- include "hap-ui.labels" . | nindent 4 }}
{{- end }}
