{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heater.serviceAccountName" . }}
  labels:
    {{- include "heater.labels" . | nindent 4 }}
{{- end }}
